---

- name: "PREREQ | Add the required packages installed | Python2"
  vars:
    ansible_python_interpreter: "{{ python2_bin }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - python2-rpm
    - libselinux-python

- name: "PREREQ | Check required packages installed | Python3"
  when: ansible_facts.python.version.major is version('3', '=')
  vars:
    ansible_python_interpreter: "{{ python2_bin }}"
  ansible.builtin.package:
    name: python3-rpm
    state: present
