---

- name: "5.1.4 | PATCH | Ensure all logfiles have appropriate access configured"
  when: amazon2cis_rule_5_1_4
  tags:
    - level1-server
    - level1-workstation
    - patch
    - NIST800-53R5_AU-2
    - NIST800-53R5_AU-12
    - logfiles
    - rule_5.1.4
  block:
    - name: "5.1.4 | AUDIT | Ensure all logfiles have appropriate access configured | find files"
      ansible.builtin.shell: |
        set -o pipefail
        find /var/log/ -type f -exec ls {} \;
      args:
        executable: "{{ amazon2cis_shell_executable }}"
      changed_when: false
      failed_when: false
      register: discovered_logfiles

    - name: "5.1.4 | AUDIT | Ensure all logfiles have appropriate access configured | Set fact"
      when:
        - item != "/var/log/btmp"
        - item != "/var/log/utmp"
        - item != "/var/log/wtmp"
        - item != "/var/log/lastlog"
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 'u-x,g-wx,o-rwx'
      failed_when: discovered_file_exists_nottmp.state not in '[ file, absent ]'
      register: discovered_file_exists_nottmp
      loop: "{{ discovered_logfiles.stdout_lines }}"

    - name: "5.1.4 | AUDIT | Ensure all logfiles have appropriate access configured | Adjust permissions"
      when:
        - discovered_system_logfiles.stdout_lines is defined
        - item == "/var/log/btmp"
        - item == "/var/log/utmp"
        - item == "/var/log/wtmp"
        - item == "/var/log/lastlog"
        - "'sssd' in item or 'SSSD' in item"
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 'ug-x,o-wx'
      failed_when: discovered_file_exists_tmp.state not in '[ file, absent ]'
      register: discovered_file_exists_tmp
      loop: "{{ discovered_logfiles.stdout_lines }}"
