---

- name: Systemd restart tmp.mount
  when: not system_is_container
  ansible.builtin.systemd:
    name: tmp.mount
    daemon_reload: true
    enabled: true
    masked: false
    state: reloaded

- name: Remount /tmp
  ansible.posix.mount:
    path: /tmp
    state: remounted

- name: Remount /dev/shm
  ansible.posix.mount:
    name: /dev/shm
    state: remounted

- name: Remount /home
  ansible.posix.mount:
    name: /home
    state: remounted

- name: Remount /var
  ansible.posix.mount:
    name: /var
    state: remounted

- name: Remount /var/tmp
  ansible.posix.mount:
    name: /var/tmp
    state: remounted

- name: Remount /var/log
  ansible.posix.mount:
    name: /var/log
    state: remounted

- name: Remount /var/log/audit
  ansible.posix.mount:
    name: /var/log/audit
    state: remounted

- name: Systemd_daemon_reload
  when: not system_is_container
  ansible.builtin.systemd:
    daemon_reload: true

- name: Rebuild_grub
  when: not system_is_container
  ansible.builtin.command: /sbin/grub2-mkconfig -o "{{ amazon2cis_bootloader_file }}"
  changed_when: true

- name: Restart_postfix
  when: not system_is_container
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Sysctl_flush_ipv4_routes
  when: not system_is_container
  ansible.posix.sysctl:
    name: net.ipv4.route.flush
    value: '1'
    sysctl_set: true
  ignore_errors: true # noqa ignore-errors

- name: Sysctl_flush_ipv6_routes
  when: not system_is_container
  ansible.posix.sysctl:
    name: net.ipv6.route.flush
    value: '1'
    sysctl_set: true
  ignore_errors: true # noqa ignore-errors

- name: Restart_rsyslog
  when: not system_is_container
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Restart_journald
  when: not system_is_container
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Restart_systemd_journal_upload
  when: not system_is_container
  ansible.builtin.service:
    name: systemd-journal-upload
    state: restarted

- name: Audit_immutable_fact
  when: discovered_auditd_immutable_check.rc == 0
  ansible.builtin.debug:
    msg: "Reboot required for auditd to apply new rules as immutable set"
  notify: Change_requires_reboot

- name: Auditd rules reload
  when: discovered_auditd_immutable_check.rc == 1 or discovered_augenrules_check.stdout is search('No change')
  ansible.builtin.command: augenrules --load
  changed_when: true
  failed_when: discovered_augenrule_load.rc not in [ 0, 1 ]
  register: discovered_augenrule_load

- name: Restart_auditd # noqa: command-instead-of-module
  when: not system_is_container
  ansible.builtin.command: /sbin/service auditd restart
  changed_when: true

- name: Restart sshd
  when: not system_is_container
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Change_requires_reboot
  ansible.builtin.set_fact:
    change_requires_reboot: true
