---

- name: "SECTION | 3.1 | Disable unused network protocols and devices"
  ansible.builtin.include_tasks: cis_3.1.x.yml

- name: "SECTION | 3.2 | Network Parameters (Host Only)"
  ansible.builtin.include_tasks: cis_3.2.x.yml

- name: "SECTION | 3.3 | Network Parameters (Host and Router)"
  ansible.builtin.include_tasks: cis_3.3.x.yml

- name: "SECTION | 3.4 | Uncommon Network Protocols"
  ansible.builtin.include_tasks: cis_3.4.x.yml

- name: "SECTION | 3.5.1 | Configure firewalld"
  ansible.builtin.include_tasks: cis_3.5.1.x.yml
  when:
  - amazon2cis_firewall == "firewalld"

- name: "SECTION | 3.5.2 | Configure nftables"
  ansible.builtin.include_tasks: cis_3.5.2.x.yml
  when:
  - amazon2cis_firewall == "nftables"

- name: "SECTION | 3.5.3.1.x | Configure iptables"
  ansible.builtin.include_tasks: cis_3.5.3.1.x.yml
  when:
  - amazon2cis_firewall == "iptables"
