---

- name: "1.3.1 | PATCH | Ensure authentication required for single user mode"
  when:
      - amazon2cis_rule_1_3_1
      - ansible_facts['distribution_major_version'] is version('2', '>=')
  tags:
      - level1
      - automated
      - patch
      - rule_1.3.1
  block:
      - name: "1.3.1 | PATCH | Ensure authentication required for single user mode | Emergency service"
        ansible.builtin.lineinfile:
            path: /usr/lib/systemd/system/emergency.service
            regexp: '/sbin/sulogin'
            line: 'ExecStart=-/bin/sh -c "/sbin/sulogin; /usr/bin/systemctl --fail --no-block default'

      - name: "1.3.1 | PATCH | Ensure authentication required for single user mode | Rescue service"
        ansible.builtin.lineinfile:
            path: /usr/lib/systemd/system/rescue.service
            regexp: '/sbin/sulogin'
            line: 'ExecStart=-/bin/sh -c "/sbin/sulogin; /usr/bin/systemctl --fail --no-block default'
