---

- name: "1.1.2.1.1 | PATCH | Ensure /tmp is a seperate partition"
  when:
      - required_mount not in mount_names
      - amazon2cis_rule_1_1_2_1_1
  tags:
      - level1
      - automated
      - patch
      - rule_1.1.2.1.1
      - mounts
      - NIST800-53R5_CM-7
  vars:
      warn_control_id: '1.1.2.1.1'
      required_mount: '/tmp'
  block:
      - name: "1.1.2.1.1 | AUDIT | Ensure /tmp is a separate partition | Absent"
        ansible.builtin.debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"

      - name: "1.1.2.1.1 | AUDIT | Ensure /tmp is a separate partition | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml

- name: |
         "1.1.2.1.2 | PATCH | Ensure nodev option set on /tmp partition
          1.1.2.1.3 | PATCH | Ensure nosuid option set on /tmp partition
          1.1.2.1.4 | PATCH | Ensure noexec option set on /tmp partition"
  when:
      - item.mount == "/tmp"
      - amazon2cis_tmp_svc
      - amazon2cis_rule_1_1_2_1_2 or
        amazon2cis_rule_1_1_2_1_3 or
        amazon2cis_rule_1_1_2_1_4
  tags:
      - level1
      - automated
      - patch
      - rule_1.1.2.1.2
      - rule_1.1.2.1.3
      - rule_1.1.2.1.4
      - mounts
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
  ansible.posix.mount:
      name: /tmp
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if amazon2cis_rule_1_1_2_1_2 %}nodev,{% endif %}{% if amazon2cis_rule_1_1_2_1_3 %}nosuid,{% endif %}{% if amazon2cis_rule_1_1_2_1_4 %}noexec{% endif %}
  notify: systemd restart tmp.mount
  with_items:
      - "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
