---

- name: "1.5.1.1 | PATCH | Ensure SELinux is installed"
  when:
      - not amazon2cis_selinux_disable
      - amazon2cis_rule_1_5_1_1
  tags:
      - level1
      - automated
      - patch
      - rule_1.5.1.1
      - selinux
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
  vars:
      ansible_python_interpreter: /bin/python
  ansible.builtin.package:
      name: libselinux
      state: present

- name: "1.5.1.2 | PATCH | Ensure SELinux is not disabled in bootloader configuration"
  when:
      - not amazon2cis_selinux_disable
      - amazon2cis_rule_1_5_1_2
  tags:
      - level1
      - automated
      - patch
      - rule_1.5.1.2
      - selinux
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
  notify: Rebuild_grub
  ansible.builtin.replace:
      path: /etc/default/grub
      regexp: '{{ item }}'
      replace: ''
  loop:
      - selinux=0
      - enforcing=0

- name: |
    "1.5.1.3 | PATCH | Ensure SELinux policy is configured
     1.5.1.4 | PATCH | Ensure the SELinux state is enforcing or permissive"
  when:
      - not amazon2cis_selinux_disable
      - amazon2cis_rule_1_5_1_3
      - amazon2cis_rule_1_5_1_4
  tags:
      - level1
      - automated
      - patch
      - rule_1.5.1.3
      - rule_1.5.1.4
      - selinux
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
  vars:
      ansible_python_interpreter: "{{ python2_bin }}"
  ansible.posix.selinux:
      conf: /etc/selinux/config
      policy: "{{ amazon2cis_selinux_pol }}"
      state: "{{ amazon2cis_selinux_state }}"

- name: "1.5.1.5 | PATCH | Ensure the SELinux state is enforcing"
  when:
      - not amazon2cis_selinux_disable
      - not amazon2cis_selinux_state == "permissive"
      - amazon2cis_rule_1_5_1_5
  tags:
      - level2
      - automated
      - patch
      - rule_1.5.1.5
      - selinux
      - NIST800-53R5_AC-3
      - NIST800-53R5_SI-6
  vars:
      ansible_python_interpreter: "{{ python2_bin }}"
  ansible.posix.selinux:
      conf: /etc/selinux/config
      policy: "{{ amazon2cis_selinux_pol }}"
      state: enforcing

- name: "1.5.1.6 | AUDIT | Ensure no unconfined services exist"
  when:
      - amazon2cis_rule_1_5_1_6
  tags:
      - level1
      - automated
      - audit
      - rule_1.5.1.6
      - selinux
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
  vars:
      warn_control_id: '1.5.1.6'
  block:
      - name: "1.5.1.6 | AUDIT | Ensure no unconfined services exist | Find the unconfined services"
        ansible.builtin.shell: ps -eZ | grep unconfined_service_t
        changed_when: false
        failed_when: false
        register: amazon2cis_1_5_1_6_unconf_services

      - name: "1.5.1.6 | AUDIT | Ensure no unconfined services exist | Message on unconfined services"
        ansible.builtin.debug:
            msg: "Warning! You have unconfined services: {{ amazon2cis_1_5_1_6_unconf_services.stdout_lines }}"
        when: amazon2cis_1_5_1_6_unconf_services.stdout | length > 0

      - name: "1.5.1.6 | AUDIT | Ensure no unconfined services exist | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml

- name: "1.5.1.7 | PATCH | Ensure the MCS Translation Service (mcstrans) is not installed"
  when:
      - amazon2cis_rule_1_5_1_7
  tags:
      - level1
      - automated
      - patch
      - rule_1.5.1.7
      - mcstrans
      - NIST800-53R5_SI-4
  vars:
      ansible_python_interpreter: /bin/python
  ansible.builtin.package:
      name: mcstrans
      state: absent

- name: "1.5.1.8 | PATCH | Ensure SETroubleshoot is not installed"
  when:
      - amazon2cis_rule_1_5_1_8
  tags:
      - level1
      - automated
      - patch
      - rule_1.5.1.8
      - selinux
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
  vars:
      ansible_python_interpreter: /bin/python
  ansible.builtin.package:
      name: setroubleshoot
      state: absent
